bkbnio/kompendium

CHANGELOG.md, gradle.properties, kompendium-core/src/main/kotlin/org/leafygreens/kompendium/Kontent.kt, kompendium-core/src/main/kotlin/org/leafygreens/kompendium/models/meta/SchemaMap.kt, kompendium-core/src/test/kotlin/org/leafygreens/kompendium/KontentTest.kt, kompendium-core/src/test/kotlin/org/leafygreens/kompendium/util/TestModels.kt
=> added special case to support UUID field

CHANGELOG.md, README.md, gradle.properties, kompendium-core/src/main/kotlin/org/leafygreens/kompendium/Kompendium.kt, kompendium-core/src/main/kotlin/org/leafygreens/kompendium/Kontent.kt, kompendium-core/src/main/kotlin/org/leafygreens/kompendium/util/Helpers.kt, kompendium-core/src/test/kotlin/org/leafygreens/kompendium/KontentTest.kt
=> refactored to leverage KType

kompendium-core/src/main/kotlin/org/leafygreens/kompendium/Kontent.kt, kompendium-core/src/main/kotlin/org/leafygreens/kompendium/util/Helpers.kt
Hi 👋 
This PR introduces a minor change to set the log level from info to debug. It reduces a lot of the default logging output when using it in another project.
=> set logging to debug

kompendium-playground/src/main/kotlin/org/leafygreens/kompendium/playground/Main.kt
just a quick playground update
=> updated playground

.github/workflows/release.yml, CHANGELOG.md, build.gradle.kts, gradle.properties
🤞 
I can see the snapshot version on nexus but really just gotta do it live to see if the release works
=> hopefully will push and release to maven

build.gradle.kts
=> maybe this

build.gradle.kts
=> fuck u nexy

.github/workflows/release.yml
nexus sucks I'm over it... Github for life
=> i give up, nexus another day i guess

CHANGELOG.md, build.gradle.kts, gradle.properties
Reddit user sufficiently embarrassed me about my bad commit message habits.. so this is sweeping that under the rug 😄 but forever people will be able to peruse my commit history and make fun of my terrible habits
Personal 
=> point well taken, this is a family show

.github/workflows/release.yml, CHANGELOG.md, README.md, build.gradle.kts, gradle.properties, kompendium-core/src/main/kotlin/io/bkbn/kompendium/KompendiumPreFlight.kt, kompendium-core/src/main/kotlin/io/bkbn/kompendium/Kontent.kt, kompendium-core/src/main/kotlin/io/bkbn/kompendium/MethodParser.kt, kompendium-core/src/main/kotlin/io/bkbn/kompendium/Notarized.kt, kompendium-core/src/main/kotlin/io/bkbn/kompendium/models/oas/OpenApiSpecComponentSchema.kt, kompendium-core/src/main/kotlin/io/bkbn/kompendium/models/oas/OpenApiSpecMediaType.kt, kompendium-core/src/main/kotlin/io/bkbn/kompendium/models/oas/OpenApiSpecReferencable.kt, kompendium-core/src/main/kotlin/io/bkbn/kompendium/util/Helpers.kt, kompendium-core/src/test/kotlin/io/bkbn/kompendium/KompendiumTest.kt, kompendium-core/src/test/kotlin/io/bkbn/kompendium/util/TestModels.kt, kompendium-core/src/test/kotlin/io/bkbn/kompendium/util/TestModules.kt, kompendium-core/src/test/kotlin/io/bkbn/kompendium/util/TestResponseInfo.kt, kompendium-core/src/test/resources/complex_type.json, kompendium-core/src/test/resources/crazy_polymorphic_example.json, kompendium-core/src/test/resources/example_req_and_resp.json, kompendium-core/src/test/resources/generic_response.json, kompendium-core/src/test/resources/notarized_post.json, kompendium-core/src/test/resources/notarized_put.json, kompendium-core/src/test/resources/polymorphic_response.json, kompendium-core/src/test/resources/polymorphic_response_with_generics.json, kompendium-playground/build.gradle.kts, kompendium-playground/src/main/kotlin/io/bkbn/kompendium/playground/Main.kt, kompendium-playground/src/main/kotlin/io/bkbn/kompendium/playground/Models.kt, kompendium-playground/src/main/kotlin/io/bkbn/kompendium/playground/PlaygroundToC.kt, kompendium-swagger-ui/src/main/kotlin/io/bkbn/kompendium/swagger/SwaggerUI.kt
Adds support for sealed classes as well as generics
Closes #40 
Closes #58 
Added several new tests, old tests still pass
=> Polymorphic and Generic Support

.github/workflows/publish.yml, .github/workflows/release.yml, CHANGELOG.md, build.gradle.kts, gradle.properties, kompendium-auth/build.gradle.kts, kompendium-core/build.gradle.kts, kompendium-swagger-ui/build.gradle.kts
Finally successfully pushed a release version to maven central.  Honestly been the hardest part of this entire project 🤦 
Closes #37 
=> Maven Central Here We Come!!

CHANGELOG.md, README.md, gradle.properties, gradle/libs.versions.toml, kompendium-auth/build.gradle.kts, kompendium-core/build.gradle.kts, kompendium-playground/build.gradle.kts, kompendium-playground/src/main/kotlin/io/bkbn/kompendium/playground/Main.kt
Adds more details around Kompendium's serializer agnostic approach.  
Part of #64 
Should not impact library
=> explicit decoupled serialization

CHANGELOG.md, gradle.properties, kompendium-core/src/main/kotlin/io/bkbn/kompendium/KompendiumPreFlight.kt, kompendium-core/src/main/kotlin/io/bkbn/kompendium/Kontent.kt, kompendium-core/src/test/kotlin/io/bkbn/kompendium/KompendiumTest.kt, kompendium-core/src/test/kotlin/io/bkbn/kompendium/util/TestModels.kt, kompendium-core/src/test/kotlin/io/bkbn/kompendium/util/TestModules.kt, kompendium-core/src/test/kotlin/io/bkbn/kompendium/util/TestResponseInfo.kt, kompendium-core/src/test/resources/polymorphic_list_response.json, kompendium-core/src/test/resources/polymorphic_map_response.json, kompendium-core/src/test/resources/sealed_interface_response.json
Addresses a bug causing polymorphic collections to not generate properly 
Closes #79 
Tests added to show fix
=> Support polymorphic collections and maps

CHANGELOG.md, README.md, kompendium-core/src/main/kotlin/io/bkbn/kompendium/Kompendium.kt, kompendium-playground/build.gradle.kts, kompendium-playground/src/main/kotlin/io/bkbn/kompendium/playground/Main.kt, kompendium-playground/src/main/kotlin/io/bkbn/kompendium/playground/Models.kt, kompendium-playground/src/main/kotlin/io/bkbn/kompendium/playground/PlaygroundToC.kt
Adds the ability to inject custom type overrides 
Closes #77 
Confirmed in the playground
=> allow custom type overrides

.github/workflows/pr_checks.yml, .github/workflows/publish.yml, CHANGELOG.md, build.gradle.kts, gradle.properties, gradle/wrapper/gradle-wrapper.properties, settings.gradle.kts
Adds code coverage reporter 
Closes #72 
Doin' it live
=> Codacy integration

CHANGELOG.md, README.md, gradle.properties, kompendium-core/src/main/kotlin/io/bkbn/kompendium/annotations/KompendiumParam.kt, kompendium-core/src/test/kotlin/io/bkbn/kompendium/KompendiumTest.kt, kompendium-core/src/test/kotlin/io/bkbn/kompendium/util/TestModels.kt, kompendium-core/src/test/kotlin/io/bkbn/kompendium/util/TestModules.kt, kompendium-core/src/test/kotlin/io/bkbn/kompendium/util/TestResponseInfo.kt, kompendium-core/src/test/resources/override_parameter_name.json
Adds a test and some documentation showcasing how to leverage Kotlin special names to create header parameters using data classes. 
Closes #113 
Added a test showcases feature
=> Example header parameter

.gitignore, CHANGELOG.md, build.gradle.kts, buildSrc/src/main/kotlin/kotlin-common-conventions.gradle.kts, dokka/index.html, gradle.properties, kompendium-auth/build.gradle.kts, kompendium-auth/src/test/kotlin/io/bkbn/kompendium/auth/KompendiumAuthTest.kt, kompendium-auth/src/test/kotlin/io/bkbn/kompendium/auth/util/TestData.kt, kompendium-auth/src/test/kotlin/io/bkbn/kompendium/auth/util/TestModels.kt, kompendium-auth/src/test/kotlin/io/bkbn/kompendium/auth/util/TestModules.kt, kompendium-core/build.gradle.kts, kompendium-core/src/test/kotlin/io/bkbn/kompendium/core/KompendiumTest.kt, kompendium-core/src/test/kotlin/io/bkbn/kompendium/core/KontentTest.kt, kompendium-core/src/test/kotlin/io/bkbn/kompendium/core/util/TestHelpers.kt, kompendium-core/src/test/kotlin/io/bkbn/kompendium/core/util/TestModules.kt, kompendium-locations/build.gradle.kts, kompendium-locations/src/test/kotlin/io/bkbn/kompendium/locations/KompendiumLocationsTest.kt, kompendium-locations/src/test/kotlin/io/bkbn/kompendium/locations/util/TestData.kt, kompendium-locations/src/test/kotlin/io/bkbn/kompendium/locations/util/TestModels.kt, kompendium-locations/src/test/kotlin/io/bkbn/kompendium/locations/util/TestModules.kt, kompendium-locations/src/test/kotlin/io/bkbn/kompendium/locations/util/TestResponseInfo.kt, kompendium-swagger-ui/build.gradle.kts
=> Kotest Integration

CHANGELOG.md, kompendium-core/src/main/kotlin/io/bkbn/kompendium/core/MethodParser.kt, kompendium-core/src/main/kotlin/io/bkbn/kompendium/core/metadata/ParameterExample.kt, kompendium-core/src/main/kotlin/io/bkbn/kompendium/core/metadata/method/DeleteInfo.kt, kompendium-core/src/main/kotlin/io/bkbn/kompendium/core/metadata/method/GetInfo.kt, kompendium-core/src/main/kotlin/io/bkbn/kompendium/core/metadata/method/HeadInfo.kt, kompendium-core/src/main/kotlin/io/bkbn/kompendium/core/metadata/method/MethodInfo.kt, kompendium-core/src/main/kotlin/io/bkbn/kompendium/core/metadata/method/OptionsInfo.kt, kompendium-core/src/main/kotlin/io/bkbn/kompendium/core/metadata/method/PatchInfo.kt, kompendium-core/src/main/kotlin/io/bkbn/kompendium/core/metadata/method/PostInfo.kt, kompendium-core/src/main/kotlin/io/bkbn/kompendium/core/metadata/method/PutInfo.kt, kompendium-core/src/test/kotlin/io/bkbn/kompendium/core/KompendiumTest.kt, kompendium-core/src/test/kotlin/io/bkbn/kompendium/core/util/TestModules.kt, kompendium-core/src/test/resources/example_parameters.json, kompendium-core/src/testFixtures/kotlin/io/bkbn/kompendium/core/fixtures/TestResponseInfo.kt, kompendium-oas/src/main/kotlin/io/bkbn/kompendium/oas/payload/Parameter.kt
Enables parameter examples to be added to the `MethodInfo`
Added new test :)
=> feat: enable creation of explicit parameter examples

CHANGELOG.md, kompendium-core/src/main/kotlin/io/bkbn/kompendium/core/DefaultMethodParser.kt, kompendium-core/src/main/kotlin/io/bkbn/kompendium/core/Notarized.kt, kompendium-core/src/main/kotlin/io/bkbn/kompendium/core/parser/IMethodParser.kt, kompendium-locations/src/main/kotlin/io/bkbn/kompendium/locations/LocationMethodParser.kt, kompendium-locations/src/main/kotlin/io/bkbn/kompendium/locations/NotarizedLocation.kt, kompendium-locations/src/test/resources/notarized_delete_nested_location.json, kompendium-locations/src/test/resources/notarized_get_nested_location.json, kompendium-locations/src/test/resources/notarized_post_nested_location.json, kompendium-locations/src/test/resources/notarized_put_nested_location.json, kompendium-oas/src/main/kotlin/io/bkbn/kompendium/oas/serialization/NumberSerializer.kt
Locations API is now scanned to inherit parameters from parent(s)
Closes #126 
Tests have been updated and all pass
=> fix: locations inheritance

CHANGELOG.md, kompendium-auth/src/test/kotlin/io/bkbn/kompendium/auth/KompendiumAuthTest.kt, kompendium-core/Module.md, kompendium-core/build.gradle.kts, kompendium-core/src/test/kotlin/io/bkbn/kompendium/core/KompendiumTest.kt, kompendium-core/src/testFixtures/kotlin/io/bkbn/kompendium/core/fixtures/SupportedSerializers.kt, kompendium-core/src/testFixtures/kotlin/io/bkbn/kompendium/core/fixtures/TestHelpers.kt, kompendium-core/src/testFixtures/kotlin/io/bkbn/kompendium/core/fixtures/TestModels.kt, kompendium-locations/src/test/kotlin/io/bkbn/kompendium/locations/KompendiumLocationsTest.kt, kompendium-oas/build.gradle.kts, kompendium-oas/src/main/kotlin/io/bkbn/kompendium/oas/schema/ComponentSchema.kt, kompendium-oas/src/main/kotlin/io/bkbn/kompendium/oas/security/SecuritySchema.kt, kompendium-oas/src/main/kotlin/io/bkbn/kompendium/oas/serialization/AnySerializer.kt, kompendium-oas/src/main/kotlin/io/bkbn/kompendium/oas/serialization/ComponentSchemaSerializer.kt, kompendium-oas/src/main/kotlin/io/bkbn/kompendium/oas/serialization/KompendiumSerializersModule.kt, kompendium-oas/src/main/kotlin/io/bkbn/kompendium/oas/serialization/NumberSerializer.kt, kompendium-oas/src/main/kotlin/io/bkbn/kompendium/oas/serialization/SecuritySchemaSerializer.kt, kompendium-playground/build.gradle.kts, kompendium-playground/src/main/kotlin/io/bkbn/kompendium/playground/AuthPlayground.kt, kompendium-playground/src/main/kotlin/io/bkbn/kompendium/playground/BasicPlayground.kt, kompendium-playground/src/main/kotlin/io/bkbn/kompendium/playground/ConstraintPlayground.kt, kompendium-playground/src/main/kotlin/io/bkbn/kompendium/playground/ExceptionPlayground.kt, kompendium-playground/src/main/kotlin/io/bkbn/kompendium/playground/GenericPlayground.kt, kompendium-playground/src/main/kotlin/io/bkbn/kompendium/playground/LocationPlayground.kt, kompendium-playground/src/main/kotlin/io/bkbn/kompendium/playground/PolymorphicPlayground.kt, kompendium-playground/src/main/kotlin/io/bkbn/kompendium/playground/RecursionPlayground.kt, kompendium-playground/src/main/kotlin/io/bkbn/kompendium/playground/SwaggerPlayground.kt, kompendium-playground/src/main/kotlin/io/bkbn/kompendium/playground/util/Util.kt
Gson, Kotlinx, and Jackson serializers are now run against every test to ensure all output remains constant across serializers. 
Closes #71
=> chore: test all serializers

CHANGELOG.md, kompendium-playground/build.gradle.kts, kompendium-playground/src/main/kotlin/io/bkbn/kompendium/playground/CustomTypePlayground.kt
Adds an example of a custom type override to the playground
=> doc: add custom type example to playground

CHANGELOG.md, kompendium-core/src/main/kotlin/io/bkbn/kompendium/core/handler/CollectionHandler.kt, kompendium-core/src/test/resources/polymorphic_list_response.json
Fix for https://github.com/bkbnio/kompendium/issues/199
=> Fix: Unable to use sealed typed collections #199

CHANGELOG.md, kompendium-core/src/main/kotlin/io/bkbn/kompendium/core/constraint/ConstraintScanner.kt, kompendium-core/src/test/kotlin/io/bkbn/kompendium/core/KompendiumTest.kt, kompendium-core/src/test/kotlin/io/bkbn/kompendium/core/util/TestModules.kt, kompendium-core/src/test/resources/formatted_date_time_string.json, kompendium-core/src/test/resources/formatted_no_format_string.json, kompendium-core/src/testFixtures/kotlin/io/bkbn/kompendium/core/fixtures/TestHelpers.kt, kompendium-core/src/testFixtures/kotlin/io/bkbn/kompendium/core/fixtures/TestModels.kt, kompendium-core/src/testFixtures/kotlin/io/bkbn/kompendium/core/fixtures/TestModules.kt, kompendium-core/src/testFixtures/kotlin/io/bkbn/kompendium/core/fixtures/TestResponseInfo.kt, kompendium-playground/src/main/kotlin/io/bkbn/kompendium/playground/CustomTypePlayground.kt
Implementation notes:
- Constraint annotations will override constraint values defined in SimpleSchema only if annotations exist
Fixes https://github.com/bkbnio/kompendium/issues/198
=> fix: formatting custom SimpleSchema (fixes #198)

CHANGELOG.md, kompendium-core/src/main/kotlin/io/bkbn/kompendium/core/handler/MapHandler.kt, kompendium-core/src/test/resources/crazy_polymorphic_example.json, kompendium-core/src/test/resources/polymorphic_error_status_codes.json, kompendium-core/src/test/resources/polymorphic_list_response.json, kompendium-core/src/test/resources/polymorphic_map_response.json, kompendium-core/src/test/resources/polymorphic_response.json, kompendium-core/src/testFixtures/kotlin/io/bkbn/kompendium/core/fixtures/TestModels.kt
fixes https://github.com/bkbnio/kompendium/issues/210
=> Support Maps with sealed class type

CHANGELOG.md, gradle.properties, kompendium-annotations/src/main/kotlin/io/bkbn/kompendium/annotations/FreeFormObject.kt, kompendium-core/src/main/kotlin/io/bkbn/kompendium/core/handler/ObjectHandler.kt, kompendium-core/src/test/kotlin/io/bkbn/kompendium/core/KompendiumTest.kt, kompendium-core/src/test/kotlin/io/bkbn/kompendium/core/util/TestModules.kt, kompendium-core/src/test/resources/free_form_field.json, kompendium-core/src/testFixtures/kotlin/io/bkbn/kompendium/core/fixtures/TestModels.kt, kompendium-core/src/testFixtures/kotlin/io/bkbn/kompendium/core/fixtures/TestResponseInfo.kt
Allows unstructured data to be declared at the top level
Closes #217 
Added test
=> fix: free form annotation can be applied to top level type

CHANGELOG.md, gradle.properties, kompendium-core/src/test/kotlin/io/bkbn/kompendium/core/KompendiumTest.kt, kompendium-core/src/test/kotlin/io/bkbn/kompendium/core/util/TestModules.kt, kompendium-core/src/test/resources/nullable_enum_field.json, kompendium-core/src/testFixtures/kotlin/io/bkbn/kompendium/core/fixtures/TestModels.kt, kompendium-core/src/testFixtures/kotlin/io/bkbn/kompendium/core/fixtures/TestResponseInfo.kt, kompendium-oas/src/main/kotlin/io/bkbn/kompendium/oas/schema/EnumSchema.kt, kompendium-playground/src/main/kotlin/io/bkbn/kompendium/playground/BasicPlayground.kt, kompendium-playground/src/main/kotlin/io/bkbn/kompendium/playground/GsonSerializationPlayground.kt
Fix bug where nullable enum fields caused runtime exception
Closes #233 
Added new unit test
=> fix: nullable enum support

CHANGELOG.md, kompendium-oas/build.gradle.kts, kompendium-oas/src/main/kotlin/io/bkbn/kompendium/oas/security/ApiKeyAuth.kt, kompendium-oas/src/test/kotlin/io/bkbn/kompendium/oas/security/ApiKeyAuthTest.kt
Fix serialization of location in api key auth configuration.
Closes #260
Published locally and tested.
=> Fix serialization of api key auth location

CHANGELOG.md, core/src/test/kotlin/io/bkbn/kompendium/core/KompendiumTest.kt, core/src/test/kotlin/io/bkbn/kompendium/core/util/TestModules.kt, core/src/test/resources/T0039__nested_generic_collection.json, core/src/test/resources/T0040__nested_generic_multiple_type_params.json, core/src/testFixtures/kotlin/io/bkbn/kompendium/core/fixtures/TestModels.kt, json-schema/src/main/kotlin/io/bkbn/kompendium/json/schema/handler/SimpleObjectHandler.kt
Type erasure was causing nested generics to not get inferred properly 
Closes #241 
Added tests
=> fix: type erasure breaking nested generics

CHANGELOG.md, core/src/test/kotlin/io/bkbn/kompendium/core/KompendiumTest.kt, core/src/test/kotlin/io/bkbn/kompendium/core/util/TestModules.kt, core/src/test/resources/T0041__nullable_reference.json, core/src/testFixtures/kotlin/io/bkbn/kompendium/core/fixtures/TestModels.kt, json-schema/src/main/kotlin/io/bkbn/kompendium/json/schema/handler/SimpleObjectHandler.kt
Fixes bug causing null references on properties to not display properly 
Closes #201 
Added test
=> fix: null ref 

core/src/test/kotlin/io/bkbn/kompendium/core/KompendiumTest.kt, core/src/test/resources/T0042__simple_recursive.json, json-schema/src/main/kotlin/io/bkbn/kompendium/json/schema/handler/SimpleObjectHandler.kt
enables recursion 
Closes #287 
=> fix: recursion

core/src/test/kotlin/io/bkbn/kompendium/core/KompendiumTest.kt, core/src/test/kotlin/io/bkbn/kompendium/core/util/TestModules.kt, core/src/test/resources/T0043__gnarly_generic_example.json, core/src/testFixtures/kotlin/io/bkbn/kompendium/core/fixtures/TestModels.kt, json-schema/src/main/kotlin/io/bkbn/kompendium/json/schema/handler/SimpleObjectHandler.kt
Fixes a bug where more complex generics were not being introspected properly 
Closes #127 
Added foozy barzo test
=> fix: complex generic breaks introspection

json-schema/src/main/kotlin/io/bkbn/kompendium/json/schema/SchemaGenerator.kt, json-schema/src/main/kotlin/io/bkbn/kompendium/json/schema/definition/TypeDefinition.kt, json-schema/src/test/kotlin/io/bkbn/kompendium/json/schema/SchemaGeneratorTest.kt, json-schema/src/test/resources/T0017__scalar_uuid.json
Adds UUID as recognized scalar type 
=> fix: uuid schema

core/src/main/kotlin/io/bkbn/kompendium/core/plugin/NotarizedRoute.kt, core/src/main/kotlin/io/bkbn/kompendium/core/util/Helpers.kt, core/src/test/kotlin/io/bkbn/kompendium/core/KompendiumTest.kt, core/src/test/kotlin/io/bkbn/kompendium/core/util/TestModules.kt, core/src/test/resources/T0044__nested_type_name.json, core/src/testFixtures/kotlin/io/bkbn/kompendium/core/fixtures/TestModels.kt, json-schema/src/main/kotlin/io/bkbn/kompendium/json/schema/util/Helpers.kt
=> fix: nested class names

CHANGELOG.md, core/build.gradle.kts, core/src/main/kotlin/io/bkbn/kompendium/core/plugin/NotarizedRoute.kt, core/src/main/kotlin/io/bkbn/kompendium/core/util/Helpers.kt, core/src/test/kotlin/io/bkbn/kompendium/core/KompendiumTest.kt, core/src/test/kotlin/io/bkbn/kompendium/core/util/TestModules.kt, core/src/test/resources/T0045__default_auth_config.json, core/src/test/resources/T0046__custom_auth_config.json, core/src/test/resources/T0047__multiple_auth_strategies.json, core/src/testFixtures/kotlin/io/bkbn/kompendium/core/fixtures/TestHelpers.kt, gradle.properties, oas/src/main/kotlin/io/bkbn/kompendium/oas/path/PathOperation.kt, playground/src/main/kotlin/io/bkbn/kompendium/playground/AuthPlayground.kt
Authentication is now auto detected via route introspection.  Explicit definition in route is only necessary when adding explicit auth scopes. 
Added tests
=> feat: auto auth detect

json-schema/src/test/kotlin/io/bkbn/kompendium/json/schema/SchemaGeneratorTest.kt, json-schema/src/test/resources/T0016__recursive_object.json
=> chore: enable recursion test

.github/workflows/release.yml, CHANGELOG.md, core/src/test/kotlin/io/bkbn/kompendium/core/KompendiumTest.kt, gradle.properties, json-schema/src/main/kotlin/io/bkbn/kompendium/json/schema/exception/UnknownSchemaException.kt, json-schema/src/main/kotlin/io/bkbn/kompendium/json/schema/handler/SimpleObjectHandler.kt
=> fix: improved error output when an unknown schema is encountered

CHANGELOG.md, core/src/main/kotlin/io/bkbn/kompendium/core/routes/Redoc.kt, playground/src/main/kotlin/io/bkbn/kompendium/playground/CustomRedocPathPlayground.kt
Adds the possibility to customize the path of documentation.
See the new playground file
=> Add possibility to customize docs path

CHANGELOG.md, docs/SUMMARY.md, docs/playground.md, docs/plugins/notarized_resources.md, locations/src/main/kotlin/io/bkbn/kompendium/locations/NotarizedLocations.kt, playground/build.gradle.kts, playground/src/main/kotlin/io/bkbn/kompendium/playground/ResourcesPlayground.kt, resources/build.gradle.kts, resources/src/main/kotlin/io/bkbn/kompendium/resources/NotarizedResources.kt, resources/src/test/kotlin/io/bkbn/kompendium/resources/KompendiumResourcesTest.kt, resources/src/test/kotlin/io/bkbn/kompendium/resources/util/TestModels.kt, resources/src/test/resources/T0001__simple_resource.json, resources/src/test/resources/T0002__nested_resources.json, settings.gradle.kts
Adds support for ktor resources plugin.
Closes #356 
Unit tests + playground
=> Add plugin to support ktor-server-resources

CHANGELOG.md, core/src/main/kotlin/io/bkbn/kompendium/core/util/Helpers.kt, core/src/test/kotlin/io/bkbn/kompendium/core/KompendiumTest.kt, core/src/test/kotlin/io/bkbn/kompendium/core/util/TestModules.kt, core/src/test/resources/T0008__complex_type.json, core/src/test/resources/T0036__nullable_fields.json, core/src/test/resources/T0037__nullable_enum_field.json, core/src/test/resources/T0040__nested_generic_multiple_type_params.json, core/src/test/resources/T0042__simple_recursive.json, core/src/test/resources/T0049__unbacked_property.json, core/src/test/resources/T0051__top_level_nullable.json, core/src/testFixtures/kotlin/io/bkbn/kompendium/core/fixtures/TestModels.kt, json-schema/src/main/kotlin/io/bkbn/kompendium/json/schema/SchemaGenerator.kt, json-schema/src/main/kotlin/io/bkbn/kompendium/json/schema/definition/EnumDefinition.kt, json-schema/src/main/kotlin/io/bkbn/kompendium/json/schema/handler/EnumHandler.kt, json-schema/src/main/kotlin/io/bkbn/kompendium/json/schema/handler/SimpleObjectHandler.kt, json-schema/src/test/kotlin/io/bkbn/kompendium/json/schema/SchemaGeneratorTest.kt, json-schema/src/test/resources/T0006__nullable_object.json, json-schema/src/test/resources/T0007__simple_enum.json, json-schema/src/test/resources/T0008__nullable_enum.json, json-schema/src/test/resources/T0021__object_with_enum.json
- feat: use references for enums (#366)
- fix: remove redundant oneOf for nullable properties (#367)
- doc: update changelog for enums and nullability
Closes #366, #367
Updated unit tests, added a new test
=> fix enums and nullability

CHANGELOG.md, core/src/main/kotlin/io/bkbn/kompendium/core/plugin/NotarizedRoute.kt, docs/plugins/notarized_resources.md, resources/src/main/kotlin/io/bkbn/kompendium/resources/Helpers.kt, resources/src/main/kotlin/io/bkbn/kompendium/resources/NotarizedResource.kt, resources/src/main/kotlin/io/bkbn/kompendium/resources/NotarizedResources.kt, resources/src/test/kotlin/io/bkbn/kompendium/resources/KompendiumResourcesTest.kt, resources/src/test/resources/T0003__resources_in_route.json
Adds a route-level plugin that is used similarly to NotarizedRoute.
Closes #370
Added unit test
=> feat: add support for NotarizedResource (#370)

.github/workflows/pr_checks.yml, .github/workflows/publish.yml, .github/workflows/release.yml, build.gradle.kts
=> chore: bump sourdough

core/src/test/kotlin/io/bkbn/kompendium/core/KompendiumTest.kt, core/src/test/kotlin/io/bkbn/kompendium/core/util/NotarizedOpenApi.kt, core/src/test/resources/T0008__complex_type.json, core/src/test/resources/T0018__polymorphic_error_status_codes.json, core/src/test/resources/T0019__generic_exception.json, core/src/test/resources/T0027__polymorphic_response.json, core/src/test/resources/T0028__polymorphic_list_response.json, core/src/test/resources/T0029__polymorphic_map_response.json, core/src/test/resources/T0032__polymorphic_response_with_generics.json, core/src/test/resources/T0033__crazy_polymorphic_example.json, core/src/test/resources/T0037__nullable_enum_field.json, core/src/test/resources/T0040__nested_generic_multiple_type_params.json, core/src/test/resources/T0042__simple_recursive.json, core/src/test/resources/T0056__enriched_nested_collection.json, core/src/test/resources/T0057__enriched_complex_generic_type.json, core/src/test/resources/T0070__sealed_interface_type_name_override.json, core/src/test/resources/T0076__list_of_enums.json, json-schema/src/main/kotlin/io/bkbn/kompendium/json/schema/KotlinXSchemaConfigurator.kt, json-schema/src/main/kotlin/io/bkbn/kompendium/json/schema/definition/EnumDefinition.kt, json-schema/src/main/kotlin/io/bkbn/kompendium/json/schema/handler/CollectionHandler.kt, json-schema/src/main/kotlin/io/bkbn/kompendium/json/schema/handler/EnumHandler.kt, json-schema/src/test/resources/T0007__simple_enum.json, json-schema/src/test/resources/T0008__nullable_enum.json, protobuf-java-converter/src/main/kotlin/io/bkbn/kompendium/protobufjavaconverter/converters/FieldDescriptiorConverters.kt, protobuf-java-converter/src/test/resources/T0002__enummessage_post.json
=> fix: enum type def

playground/build.gradle.kts, playground/src/main/kotlin/io/bkbn/kompendium/playground/YamlPlayground.kt
=> chore: yaml example

CHANGELOG.md, core/src/test/kotlin/io/bkbn/kompendium/core/KompendiumEnrichmentTest.kt, core/src/test/kotlin/io/bkbn/kompendium/core/util/Enrichment.kt, core/src/test/resources/T0078__enriched_top_level_map.json, docs/concepts/enrichment.md, docs/index.md, docs/playground.md, docs/plugins/notarized_application.md, gradle.properties, playground/src/main/kotlin/io/bkbn/kompendium/playground/HiddenDocsPlayground.kt
=> docs: update docs for 4.0 release

docs/concepts/enrichment.md, docs/index.md, docs/playground.md, docs/plugins/notarized_application.md, docs/plugins/notarized_locations.md, docs/plugins/notarized_resources.md
=> chore: rollback docs due to sonatype disaster
